'use strict';

const ACTIONS = {
  OPEN: 'open',
  HISTORY: 'history',
  BACK_TO_CARD: 'open',
  GIVE: 'give',
  SELECT_GIVE_DURATION: 'selectGiveDuration',
  APPLY_GIVE_PRESET: 'applyGivePreset',
  TOGGLE_GIVE_COMPONENT: 'toggleGiveComponent',
  INCREMENT_GIVE_COMPONENT: 'incrementGiveComponent',
  DECREMENT_GIVE_COMPONENT: 'decrementGiveComponent',
  CLEAR_GIVE_COMPONENTS: 'clearGiveComponents',
  FINISH_GIVE_COMPONENTS: 'finishGiveComponents',
  BACK_TO_GIVE_COMPONENTS: 'backToGiveComponents',
  CONFIRM_GIVE: 'confirmGive',
  ADD_MORE_GIVE_CART: 'addMoreGiveCart',
  CONFIRM_GIVE_CART: 'confirmGiveCart',
  CLEAR_GIVE_CART: 'clearGiveCart',
  REMOVE_FROM_GIVE_CART: 'removeFromGiveCart',
  RETURN: 'return',
  RETURN_ALL_MY: 'returnAllMy',
  EXTEND: 'extend',
  EXTEND_ALL_MY: 'extendAllMy',
  TOGGLE_MY_EQUIPMENT_SELECTION: 'toggleMyEquipmentSelection',
  TOGGLE_ALL_MY_EQUIPMENT_SELECTION: 'toggleAllMyEquipmentSelection',
  CONFIRM_MY_EQUIPMENT_SELECTION: 'confirmMyEquipmentSelection',
  CANCEL_MY_EQUIPMENT_SELECTION: 'cancelMyEquipmentSelection',
  REPAIR: 'repair',
  FROM_REPAIR: 'fromRepair',
  EDIT: 'edit',
  DELETE: 'delete',
  CONFIRM_DELETE: 'confirmDelete',
};

const ACTIONS_REGEX = {
  OPEN: /^open_(\d+)$/,
  HISTORY: /^history_(\d+)(?:_(\d+))?$/,
  GIVE: /^give_(\d+)$/,
  SELECT_GIVE_DURATION: /^selectGiveDuration_(\d+)_(\d+)$/,
  APPLY_GIVE_PRESET: /^applyGivePreset_(\d+)_(minimal|full|clear)$/,
  TOGGLE_GIVE_COMPONENT: /^toggleGiveComponent_(\d+)_(.+)$/,
  INCREMENT_GIVE_COMPONENT: /^incrementGiveComponent_(\d+)_(.+)$/,
  DECREMENT_GIVE_COMPONENT: /^decrementGiveComponent_(\d+)_(.+)$/,
  CLEAR_GIVE_COMPONENTS: /^clearGiveComponents_(\d+)$/,
  FINISH_GIVE_COMPONENTS: /^finishGiveComponents_(\d+)$/,
  BACK_TO_GIVE_COMPONENTS: /^backToGiveComponents_(\d+)$/,
  CONFIRM_GIVE: /^confirmGive_(\d+)$/,
  ADD_MORE_GIVE_CART: /^addMoreGiveCart$/,
  CONFIRM_GIVE_CART: /^confirmGiveCart$/,
  CLEAR_GIVE_CART: /^clearGiveCart$/,
  REMOVE_FROM_GIVE_CART: /^removeFromGiveCart_(\d+)$/,
  RETURN: /^return_(\d+)$/,
  RETURN_ALL_MY: /^returnAllMy$/,
  EXTEND: /^extend_(\d+)$/,
  EXTEND_ALL_MY: /^extendAllMy$/,
  TOGGLE_MY_EQUIPMENT_SELECTION: /^toggleMyEquipmentSelection_(extend|return)_(\d+)$/,
  TOGGLE_ALL_MY_EQUIPMENT_SELECTION: /^toggleAllMyEquipmentSelection_(extend|return)$/,
  CONFIRM_MY_EQUIPMENT_SELECTION: /^confirmMyEquipmentSelection_(extend|return)$/,
  CANCEL_MY_EQUIPMENT_SELECTION: /^cancelMyEquipmentSelection$/,
  REPAIR: /^repair_(\d+)$/,
  FROM_REPAIR: /^fromRepair_(\d+)$/,
  EDIT: /^edit_(\d+)$/,
  DELETE: /^delete_(\d+)$/,
  CONFIRM_DELETE: /^confirmDelete_(\d+)$/,
};

module.exports = { ACTIONS, ACTIONS_REGEX };
